version: "3.7"
services:
  app:
    build:
      args:
        user: translationAgency
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php:8.4-fpm
    container_name: translationAgency-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - translationAgency

  nginx:
    image: nginx:alpine
    container_name: translationAgency-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - translationAgency

networks:
  translationAgency:
    driver: bridge
